name: Lyrical
version: '${version}'
main: moe.illusory.lyrical.Lyrical
api-version: '1.21'
authors: [ Qlickly_ ]
description: Browser-based voice chat for Minecraft

commands:
  lyrical:
    description: Get voice chat connection link
    usage: /lyrical
    permission: lyrical.use

permissions:
  lyrical.use:
    description: Allows using voice chat
    default: true
